# Generated by Django 2.2.5 on 2021-01-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_manipulations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_gallery',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='image_manipulations.Tags'),
        ),
    ]
