# Generated by Django 2.2.5 on 2021-01-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_manipulations', '0002_auto_20210102_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_gallery',
            name='tags',
        ),
        migrations.AddField(
            model_name='image_gallery',
            name='tags',
            field=models.ManyToManyField(to='image_manipulations.Tags'),
        ),
    ]
